site_name: Your Product Documentation
site_description: Documentation and guides for your product
site_url: https://public-trezir-wallt.readthedocs.io/en/latest/
theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Products:
    - Overview: products/overview.md
  - Learn & Support:
    - Getting Started: learn/getting-started.md
    - Support: learn/support.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - sitemap:
      site_url: https://public-trezir-wallt.readthedocs.io/en/latest/